// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Navbar />
//         {children}
//       </body>
//     </html>
//   );
// }

// ============================================
// 1. UPDATE: app/layout.tsx
// ============================================
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";

// Load custom fonts
const fontRegular = localFont({
  src: "../public/fonts/regular.otf",
  variable: "--font-regular",
});

const fontMedium = localFont({
  src: "../public/fonts/medium.otf",
  variable: "--font-medium",
});

const fontSemibold = localFont({
  src: "../public/fonts/semibold.otf",
  variable: "--font-semibold",
});

const fontBold = localFont({
  src: "../public/fonts/bold.otf",
  variable: "--font-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontRegular.variable} ${fontMedium.variable} ${fontSemibold.variable} ${fontBold.variable}`}
    >
      <body className="antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
